### PR TITLE
Implement longer image sequence

### PR DESCRIPTION
**Pull request by shiftsave**
Implements a longer image sequence with a function to easily swap the frames and sequence  in the future.

### CODE REVIEW

**Comment by shiftsave** [comment]
@hudakdidit Crazy how good this works with slick, I changed the frame-rate and added a real test animation and the comparison between the video output and the sequence player is almost unnoticeable.

**Comment by hudakdidit** [comment]
@shiftsave rad! I'll check it out later. You didn't like my shitty ball animation? :-P

**Comment by shiftsave** [comment]
Loved it! BUT.. too short and without something to compare it to it was hard to make up if playback was close to actual video frame-rate ;)

**Comment by hudakdidit** [comment]
@shiftsave maybe just remove that console log and check in? You can deploy to the gh-page by running `yarn deploy`

**Pull request merged**
